# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "push new build to testflight"
  lane :beta do 
    match(type: "appstore")
    build_app(scheme: "water-consumption-app-rp")
    upload_to_testflight
  end
  lane :prod do 
      deliver(
        build_number: latest_testflight_build_number.to_s,
        submit_for_review: false,
        automatic_release: false,
        force: true, # Skip HTMl report verification
        skip_metadata: false,
        skip_screenshots: true,
        skip_binary_upload: true
      )

  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "water-consumption-app-rp.xcworkspace", scheme: "water-consumption-app-rp")
    upload_to_app_store
  end
  lane :prod do 

  end
end
